//------------------------------------------------------------------------
// Copyright(c) 2025 MinMax.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"QBStrum.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"QBStrum VST3 (64Bit)"
#else
#define stringFileDescription	"QBStrum VST3"
#endif
#define stringCompanyName		"MinMax\0"
#define stringLegalCopyright	"Copyright(c) 2025 MinMax."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
